---
# ====== Application: Customers ==============================
id: 100
identification: 
  name: Customers
  alias: CUSTOMERS
  version: 24.1.0
  application-group: Starter Apps # 170324572796148244

row-search: 
  tokenize: false
  text-query-function: None

availability: 
  status: Available with Developer Toolbar
  build-status: Run and Build Application

error-handling: 
  default-display-location: Inline with Field and in Notification
  error-handling-function: eba_cust_fw.apex_error_handling

report-printing: 
  type: Use Instance Settings

advanced: 
  friendly-urls: true
  allow-feedback: false
  logging: true
  debugging: true
  compatibility-mode: 21.2 to 24.1
  accessible-read-only-items: true
  pass-ecid: N
  copyright-banner: |
    Name: #APP_NAME#
    Copyright (c)2012, #YEAR# Oracle and/or its affiliates.
    Licensed under the Universal Permissive License v 1.0 as shown 
    at https://oss.oracle.com/licenses/upl/

authentication: 
  public-user: APEX_PUBLIC_USER
  authentication-scheme: Application Express Accounts # 17806491741212844779

authorization: 
  authorization-scheme: APPLICATION SENTRY # 15972838586066895804
  run-on-public-pages: false
  run-on-background-job: true
  source-for-role-or-group-schemes: Access Control User Role Assignments

session-management: 
  rejoin-sessions: Enabled for Public Sessions
  maximum-session-length: 28800
  maximum-session-idle-time: 28800

session-state-protection: 
  enabled: true

security: 
  deep-linking: Enabled
  browser-cache: Disabled
  embed-in-frames: Allow from same origin
  referrer-policy: strict-origin
  html-escaping-mode: Extended
  runtime-api-usage: 
  - Modify This Application

database-session: 
  parsing-schema: DEV1

globalization: 
  primary-language: English (United States) (en-us)
  document-direction: Left-To-Right
  language-derived-from: Application Primary Language
  automatic-time-zone: false
  automatic-csv-encoding: false

application-format-masks: 
  date: DS
  timestamp: DS

character-value-comparison: 
  behavior: Database session NLS setting (default)

logo: 
  type: Text
  text: '&APPLICATION_TITLE.'

progressive-web-app: 
  enable: false

navigation: 
  home-url: 
    url: 'f?p=&APP_ID.:59:&SESSION.'
    page: 59 # Customers

navigation-menu: 
  list-template: Side Navigation Menu
  template-options: 
  - '#DEFAULT#'
  - js-defaultCollapsed
  - js-navCollapsed--hidden
  - t-TreeNav--styleA
  list-position: Side
  list: Application Navigation # 14865545386833462339

navigation-bar: 
  implementation: List
  list: Navigation Bar # 14879853216675126143
  list-template: Navigation Bar

javascript: 
  include-deprecated-or-desupported-javascript-functions: 
  - Pre 18.1
  - 18.x
  include-jquery-migrate: false

css: 
  file-urls: 
  - '#IMAGE_PREFIX#pkgapp_ui/css/5.0#MIN#.css'

attributes: 
  theme: Universal Theme # 42
  global-page: 0
  enable-end-users-to-choose-theme-style: true
  add-"built-with-apex"-to-footer: true
  auto-dismiss-success-messages: false

substitutions: 
- # ====== Substitution: APP_DATE_FORMAT =======================
  id: 1
  identification: 
    name: APP_DATE_FORMAT

  value: 
    static-value: DD-MON-YYYY

- # ====== Substitution: GETTING_STARTED_URL ===================
  id: 2
  identification: 
    name: GETTING_STARTED_URL

  value: 
    static-value: 'http://www.oracle.com/technetwork/developer-tools/apex/index.html'

- # ====== Substitution: APP_DATETIME_FORMAT ===================
  id: 3
  identification: 
    name: APP_DATETIME_FORMAT

  value: 
    static-value: 'DD-MON-YYYY HH24:MI'

- # ====== Substitution: APP_NAME ==============================
  id: 4
  identification: 
    name: APP_NAME

  value: 
    static-value: Customers

component-settings: 
- # ====== Component Setting: NATIVE_STAR_RATING ===============
  id: 9033763249125171
  identification: 
    name: NATIVE_STAR_RATING
    type: Item

  settings: 
    attribute-1: fa-star
    attribute-4: '#VALUE#'

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_OPEN_AI_ASSISTANT =========
  id: 9209253352099730
  identification: 
    name: NATIVE_OPEN_AI_ASSISTANT
    type: Dynamic Action

  subscription: 
    version-number: 37167665066540

- # ====== Component Setting: NATIVE_SELECT_MANY ===============
  id: 9209640779099730
  identification: 
    name: NATIVE_SELECT_MANY
    type: Item

  settings: 
    attribute-1: separated

  subscription: 
    version-number: 37167665066540

- # ====== Component Setting: NATIVE_GEOCODING =================
  id: 9232999499947599
  identification: 
    name: NATIVE_GEOCODING
    type: Process

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER

  subscription: 
    version-number: 155458166

- # ====== Component Setting: NATIVE_GEOCODED_ADDRESS ==========
  id: 107548346181515721
  identification: 
    name: NATIVE_GEOCODED_ADDRESS
    type: Item

  settings: 
    attribute-1: RELAX_HOUSE_NUMBER
    attribute-2: N
    attribute-3: 'POPUP:ITEM'
    attribute-4: default
    attribute-6: LIST

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_MAP_REGION ================
  id: 128604042938918248
  identification: 
    name: NATIVE_MAP_REGION
    type: Region

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_DATE_PICKER_APEX ==========
  id: 130917508084105283
  identification: 
    name: NATIVE_DATE_PICKER_APEX
    type: Item

  settings: 
    attribute-1: 'MONTH-PICKER:YEAR-PICKER'
    attribute-2: VISIBLE
    attribute-3: 15
    attribute-4: FOCUS

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_SINGLE_CHECKBOX ===========
  id: 183832629891133636
  identification: 
    name: NATIVE_SINGLE_CHECKBOX
    type: Item

  settings: 
    attribute-1: Y
    attribute-2: N

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_ADFBC =====================
  id: 614425838648251347
  identification: 
    name: NATIVE_ADFBC
    type: REST Data Source

  subscription: 
    version-number: 37166093824739

- # ====== Component Setting: NATIVE_IR ========================
  id: 1841995218421300319
  identification: 
    name: NATIVE_IR
    type: Region

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_COLOR_PICKER ==============
  id: 1927868381117246156
  identification: 
    name: NATIVE_COLOR_PICKER
    type: Item

  settings: 
    attribute-1: FULL
    attribute-2: POPUP

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_YES_NO ====================
  id: 14550219158869255128
  identification: 
    name: NATIVE_YES_NO
    type: Item

  settings: 
    attribute-1: Y
    attribute-3: N
    attribute-5: SWITCH

  subscription: 
    version-number: 37166093824741

- # ====== Component Setting: NATIVE_DISPLAY_SELECTOR ==========
  id: 15197089145551162601
  identification: 
    name: NATIVE_DISPLAY_SELECTOR
    type: Region

  subscription: 
    version-number: 37166093824741

